// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfrbkgsziylhmcznlnwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmcmJrZ3N6aXlsaG1jem5sbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDk0OTksImV4cCI6MjA3MzU4NTQ5OX0.HLg1w9BuK6-9e9lYvTje2GQLDBcWC3y-Ayg1duQUDls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});